### PR TITLE
Switch output of TRACE_ACTIONS from Console.Error to Debug

### PR DESCRIPTION
**Pull request by Georgy-Losenkov**
Sometimes debugging using test project is very useful but Visual Studio hides its' console output. In this case the only option is to use Debug.Write and Debug.WriteLine

### CODE REVIEW

**Comment by Georgy-Losenkov** [comment]
@ernstc, please look

**Comment by ernstc** [comment]
Hi @Georgy-Losenkov,

if you need to redirect the Console output to the Debug output, you don't need to change this code.
In your unit tests you can define a class derived from TextWriter and then assign it to the Console.Out.

```csharp
 public class DebugOutput : System.IO.TextWriter
 {
     public override void Write(char[] buffer, int index, int count)
     {
         System.Diagnostics.Debug.Write(new String(buffer, index, count));
     }

     public override void Write(string value)
     {
         System.Diagnostics.Debug.Write(value);
     }

     public override Encoding Encoding
     {
         get { return System.Text.Encoding.UTF8; }
     }
 }


Console.SetOut(new DebugOutput());
```

Anyway, I leave this open for having more clarifications on your use case context.

Thanks.

**Comment by Georgy-Losenkov** [comment]
Good point. This makes that PR unnecessary

Thank you.

**Comment by Georgy-Losenkov** [comment]
I will cancel PR.

**Pull request closed without merging**
